IF db_id('DACDB') IS NULL 
    CREATE DATABASE DACDB;
GO
CREATE TABLE DACDB.dbo.Patients (
    Id INT PRIMARY KEY IDENTITY,
    Name NVARCHAR(100) NOT NULL,
    SIN NVARCHAR(20) NOT NULL,
    Address NVARCHAR(255) NOT NULL,
    Phone NVARCHAR(20) NOT NULL
);
CREATE TABLE DACDB.dbo.Users (
    UserName NVARCHAR(100) NOT NULL,
    Password NVARCHAR(80) NOT NULL,
    Role NVARCHAR(20) NOT NULL
);

